### ISSUE TITLE
Small typo in the getting started section

### ISSUE THREAD

**Issue by swaechter** [mjhea0/typescript-node-api#2]
Thank you for your great Typescript example! I just found a small typo in the 'Want to use this project?' section of the README.md file:

Wrong: gulp script
Correct: gulp scriptS

A small but important typo ;)

**Comment by oferze** [comment]
I just fixed it in https://github.com/mjhea0/typescript-node-api/pull/3 , hope @mjhea0 will merge it soon!

BTW you can do this instead of submitting an issue, completely in GitHub.
