### ISSUE TITLE
Can't find test files on Windows

### ISSUE THREAD

**Issue by cliffeby** [mjhea0/typescript-node-api#7]
Individual tests run fine and pass, but **npm test** reports:
`Warning: Could not find any test files matching pattern: 'test/**/*.test.ts'
No test files found
npm ERR! Test failed.  See above for more details.`

Seems to be a common issue with Typescript, mocha and windows.  Haven't seen a good solution.

**Comment by ondrej-osnet-cz** [comment]
I had same issue. Remove single quote in package.json helped me:
`"test": "mocha --reporter spec --compilers ts:ts-node/register test/**/*.test.ts"`

**Comment by ianrussel** [comment]
This how it worked in my Windows 10

           "test": "mocha --reporter spec --require ts-node/register \"./test/**/*.test.ts\""

**Comment by wildan3105** [comment]
Same case here in windows 7. Still not resolved. @mjhea0

**Comment by mjhea0** [comment]
I don't have a windows box so it's really difficult for me to test this out. What error are you getting?

**Comment by wildan3105** [comment]
Same as @cliffeby got. I've tried different ways to register `*.test.ts` file but still getting the same error : file not found.

**Comment by xurei** [comment]
Having the same issue.

**Comment by umbravi** [comment]
Unix need single quotes to not have ** combined to * when the script is run. Windows needs the path to be double-quoted.

Will not work on windows:
```
'test/**/*.test.ts' 
```

Works on windows:
```
"test/**/*.test.ts"
```

If you are working on a project with others with different OS, then I suggest reading this comment: [implement scripty](https://github.com/OfficeDev/generator-office/issues/115#issuecomment-393309476)
